language: go

sudo: false

go:
  - 1.7
  - 1.8
  - 1.9

before_install:
  - go get golang.org/x/text/transform
  - go get golang.org/x/text/unicode/norm

script:
  - go test -v -covermode=count -coverprofile=coverage.out